// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:string,arg2:number,arg3:string):Promise<models.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTaskStats():Promise<models.TaskStats>;

export function GetTasks(arg1:string,arg2:string):Promise<Array<models.Task>>;

export function ToggleTask(arg1:string):Promise<models.Task>;
