// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetTaskStats() {
  return window['go']['main']['App']['GetTaskStats']();
}

export function GetTasks(arg1, arg2) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}
